#!/usr/bin/env python3
"""
ollama_codegen.py — Multi-model code generation pipeline via Ollama.

Usage:
    python ollama_codegen.py <task_file> [options]

Options:
    --output-dir, -o    Directory for attempts/ and success.py  (default: .)
    --max-iterations,-n Maximum generation attempts              (default: 20)
    --models, -m        Coder model names (space-separated)
    --manager           Manager model name                       (default: llama3)
    --timeout           Seconds before killing a test run        (default: 15)
    --no-sandbox        Skip dangerous-import check (use with care)

Task file sections:
    TASK:             Natural-language description of what the script must do
    EXPECTED_OUTPUT:  Exact stdout the script must produce
    INPUT_DATA:       (optional) stdin piped into the generated script
    TEST_ARGS:        (optional) CLI args passed to the generated script
    TEST:             (optional, repeatable) assert-style test lines
    TEST_SCRIPT:      (optional) path to an external test file to run

See task_example.txt for a complete example.

Generated by claude
"""

import argparse
import json
import re
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

import requests

# ── Configuration ─────────────────────────────────────────────────────────────

OLLAMA_BASE_URL    = "http://localhost:11434"
DEFAULT_MAX_ITER   = 20
DEFAULT_OUTPUT_DIR = "."
MANAGER_MODEL      = "llama3"
DEFAULT_MODELS     = ["deepseek-coder", "codellama", "mistral"]
SCRIPT_TIMEOUT     = 15

# Imports that generated code must not contain (sandbox shield)
DANGEROUS_IMPORTS = {
    "os", "sys", "shutil", "subprocess", "socket",
    "pathlib", "glob", "fnmatch", "signal", "ctypes",
    "importlib", "multiprocessing", "threading",
}


# ── Ollama API helpers ─────────────────────────────────────────────────────────

def ollama_chat(
    model: str,
    messages: list[dict],
    temperature: float = 0.2,
    json_schema: dict | None = None,
) -> str:
    """
    POST to Ollama /api/chat.
    Pass json_schema to enforce structured JSON output at the API layer,
    bypassing model tendency to wrap responses in prose or markdown.
    """
    payload: dict = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {"temperature": temperature},
    }
    if json_schema:
        payload["format"] = json_schema

    url = f"{OLLAMA_BASE_URL}/api/chat"
    try:
        resp = requests.post(url, json=payload, timeout=180)
        resp.raise_for_status()
    except requests.exceptions.ConnectionError:
        sys.exit(f"[FATAL] Cannot reach Ollama at {OLLAMA_BASE_URL}. Is it running?")
    except requests.exceptions.HTTPError as exc:
        sys.exit(f"[FATAL] Ollama HTTP error for '{model}': {exc}")

    return resp.json()["message"]["content"]


def list_ollama_models() -> list[str]:
    """Return base names (no tag) of locally pulled models."""
    try:
        resp = requests.get(f"{OLLAMA_BASE_URL}/api/tags", timeout=10)
        resp.raise_for_status()
        return [m["name"].split(":")[0] for m in resp.json().get("models", [])]
    except Exception:
        return []


# ── Task file parser ───────────────────────────────────────────────────────────

def parse_task_file(path: str) -> dict:
    """
    Parse a structured task file.  Supports multi-line sections and
    repeatable TEST: blocks.

    Returns a dict with keys:
        task, expected_output, input_data, test_args,
        inline_tests (list[str]), test_script (str|None)
    """
    text = Path(path).read_text()
    KEYS = {"TASK", "EXPECTED_OUTPUT", "INPUT_DATA", "TEST_ARGS", "TEST", "TEST_SCRIPT"}

    sections: dict[str, list[str]] = {k: [] for k in KEYS}
    inline_tests: list[str] = []

    current_key: str | None = None
    current_lines: list[str] = []

    def _flush():
        nonlocal current_key, current_lines
        if current_key:
            value = "\n".join(current_lines).strip()
            if current_key == "TEST":
                inline_tests.append(value)
            else:
                sections[current_key] = [value]
        current_key = None
        current_lines = []

    for line in text.splitlines():
        m = re.match(rf"^({'|'.join(KEYS)})\s*:", line)
        if m:
            _flush()
            current_key = m.group(1)
            rest = line[m.end():].strip()
            current_lines = [rest] if rest else []
        elif current_key:
            current_lines.append(line)
    _flush()

    def _get(key: str, default: str = "") -> str:
        return sections[key][0] if sections[key] else default

    task_text = _get("TASK")
    expected  = _get("EXPECTED_OUTPUT")

    if not task_text:
        sys.exit("[FATAL] Task file must contain a TASK: section.")
    if not expected and not inline_tests and not _get("TEST_SCRIPT"):
        sys.exit("[FATAL] Task file must contain EXPECTED_OUTPUT:, TEST:, or TEST_SCRIPT:.")

    raw_args = _get("TEST_ARGS")
    return {
        "task":           task_text,
        "expected_output": expected,
        "input_data":     _get("INPUT_DATA"),
        "test_args":      raw_args.split() if raw_args else [],
        "inline_tests":   inline_tests,
        "test_script":    _get("TEST_SCRIPT") or None,
    }


# ── Manager: initial plan ──────────────────────────────────────────────────────

def manager_plan(task: dict, available: list[str]) -> list[str]:
    """
    Ask the manager to choose and order coder models for this task.
    Uses Ollama structured output (format=JSON schema) so the response
    is guaranteed to be valid JSON — no regex fragility.
    """
    schema = {
        "type": "object",
        "properties": {
            "models": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Ordered list of model names to use"
            }
        },
        "required": ["models"]
    }

    model_list = "\n".join(f"  - {m}" for m in available)
    prompt = textwrap.dedent(f"""
        You are the orchestration manager for a Python code-generation pipeline.
        Choose which models should attempt the task and the order they should run.

        Available models:
        {model_list}

        Task:
        {task['task']}

        Rules:
        - Prefer coding-specialised models (deepseek-coder, codellama) for code tasks.
        - Put the strongest / most specialised model first.
        - Include 2–4 models.
        - Return a JSON object with a "models" array, e.g. {{"models": ["deepseek-coder", "mistral"]}}
    """).strip()

    raw = ollama_chat(
        MANAGER_MODEL,
        [{"role": "user", "content": prompt}],
        temperature=0.1,
        json_schema=schema,
    )

    try:
        order = json.loads(raw).get("models", [])
        valid = [m for m in order if m in available]
        if valid:
            print(f"[MANAGER] Initial model order: {valid}")
            return valid
    except (json.JSONDecodeError, AttributeError):
        pass

    print("[MANAGER] Could not parse plan; using default model order.")
    return available


# ── Manager: per-iteration routing ────────────────────────────────────────────

def manager_route(
    task: dict,
    available: list[str],
    history: list[dict],
) -> dict:
    """
    After a failure, ask the manager which model to try next and why.
    Returns {"next_model": str, "reason": str, "feedback": str}
    """
    schema = {
        "type": "object",
        "properties": {
            "next_model": {"type": "string"},
            "reason":     {"type": "string"},
            "feedback":   {"type": "string"},
        },
        "required": ["next_model", "reason", "feedback"],
    }

    # Build a concise history summary (last 3 attempts to stay within context)
    history_text = ""
    for h in history[-3:]:
        history_text += textwrap.dedent(f"""
            --- Attempt {h['attempt']} | model: {h['model']} ---
            STDOUT : {h['stdout'] or '(none)'}
            STDERR : {h['stderr'] or '(none)'}
            CODE (first 40 lines):
            {chr(10).join(h['code'].splitlines()[:40])}
        """)

    model_list = ", ".join(available)
    prompt = textwrap.dedent(f"""
        You are managing a code-generation pipeline. The last attempt failed.
        Choose which model should attempt next and write precise fixing feedback.

        TASK:
        {task['task']}

        EXPECTED OUTPUT:
        {task['expected_output']}

        AVAILABLE MODELS: {model_list}

        RECENT ATTEMPTS:
        {history_text.strip()}

        Return JSON:
        {{
          "next_model": "<one of the available model names>",
          "reason": "<why you chose this model>",
          "feedback": "<concrete bullet-point fixes for the next coder>"
        }}
    """).strip()

    raw = ollama_chat(
        MANAGER_MODEL,
        [{"role": "user", "content": prompt}],
        temperature=0.2,
        json_schema=schema,
    )

    try:
        result = json.loads(raw)
        if result.get("next_model") not in available:
            result["next_model"] = available[0]
        return result
    except (json.JSONDecodeError, AttributeError):
        return {
            "next_model": available[0],
            "reason":     "Could not parse manager response; defaulting.",
            "feedback":   "",
        }


# ── Code generation ────────────────────────────────────────────────────────────

def generate_code(model: str, task: dict, history: list[dict], feedback: str = "") -> str:
    """
    Ask a coder model to generate (or repair) a Python script.
    Passes the full history of prior attempts so it can learn from them.
    Accepts markdown code fences and strips them after the fact.
    """
    prior_attempts = ""
    for h in history[-3:]:
        prior_attempts += textwrap.dedent(f"""
            ### Attempt {h['attempt']} (by {h['model']})
            ```python
            {h['code']}
            ```
            stdout : {h['stdout'] or '(none)'}
            stderr : {h['stderr'] or '(none)'}
        """)

    system = (
        "You are an expert Python programmer. "
        "Produce a single, complete, immediately runnable Python script. "
        "You may wrap it in a ```python ... ``` code block if you wish."
    )

    user_parts = [
        f"TASK:\n{task['task']}",
        f"EXPECTED OUTPUT (stdout must match exactly after strip):\n{task['expected_output']}",
    ]
    if task["input_data"]:
        user_parts.append(f"INPUT (provided via stdin):\n{task['input_data']}")
    if task["inline_tests"]:
        tests = "\n".join(task["inline_tests"])
        user_parts.append(f"INLINE TESTS (must all pass):\n{tests}")
    if prior_attempts:
        user_parts.append(f"PRIOR FAILED ATTEMPTS (do not repeat these mistakes):\n{prior_attempts.strip()}")
    if feedback:
        user_parts.append(f"REVIEWER FEEDBACK (fix these issues):\n{feedback}")

    user = "\n\n".join(user_parts)

    response = ollama_chat(
        model,
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        temperature=0.3,
    )

    # Accept and strip markdown fences (models are fine-tuned to produce them)
    code = response.strip()
    # Remove outer ```python ... ``` or ``` ... ```
    code = re.sub(r"^```(?:python)?\s*\n", "", code)
    code = re.sub(r"\n```\s*$", "", code)
    return code.strip()


# ── Sandbox check ──────────────────────────────────────────────────────────────

def _check_dangerous_imports(code: str) -> list[str]:
    """
    Return a list of dangerous module names imported by the code.
    Checks both 'import X' and 'from X import ...' forms.
    """
    found = []
    for line in code.splitlines():
        line = line.strip()
        m = re.match(r"^(?:import|from)\s+([\w.]+)", line)
        if m:
            top = m.group(1).split(".")[0]
            if top in DANGEROUS_IMPORTS:
                found.append(top)
    return found


# ── Script testing ─────────────────────────────────────────────────────────────

def test_script(
    code: str,
    task: dict,
    timeout: int,
    sandbox: bool,
) -> tuple[bool, str, str]:
    """
    Write code to a cross-platform temp file and execute it.
    Returns (success, stdout, stderr).

    Testing strategy (in order):
      1. EXPECTED_OUTPUT exact match
      2. INLINE_TESTS  (assert lines appended and executed)
      3. TEST_SCRIPT   (external .py run against the generated module)
    """
    # Sandbox: block dangerous imports before executing anything
    if sandbox:
        bad = _check_dangerous_imports(code)
        if bad:
            return False, "", f"[SANDBOX] Blocked dangerous import(s): {', '.join(bad)}"

    # Write to a secure OS-managed temp file (cross-platform)
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(code)
        tmp_path = tmp.name

    try:
        cmd = [sys.executable, tmp_path] + task["test_args"]
        input_bytes = task["input_data"].encode() if task["input_data"] else None

        result = subprocess.run(
            cmd,
            input=input_bytes,
            capture_output=True,
            timeout=timeout,
        )
        stdout = result.stdout.decode(errors="replace").strip()
        stderr = result.stderr.decode(errors="replace").strip()

        # ── 1. Exact stdout match ─────────────────────────────────────────────
        if task["expected_output"]:
            if stdout == task["expected_output"].strip():
                # Also run inline tests if present
                if task["inline_tests"]:
                    ok, _, err = _run_inline_tests(code, task["inline_tests"], timeout, sandbox)
                    if not ok:
                        return False, stdout, err
                return True, stdout, stderr
            else:
                return False, stdout, stderr

        # ── 2. Inline assert tests only (no expected_output) ─────────────────
        if task["inline_tests"]:
            return _run_inline_tests(code, task["inline_tests"], timeout, sandbox)

        # ── 3. External test script ───────────────────────────────────────────
        if task["test_script"]:
            return _run_test_script(tmp_path, task["test_script"], timeout)

        return False, stdout, "No test criterion found."

    except subprocess.TimeoutExpired:
        return False, "", f"Script timed out after {timeout}s"
    except Exception as exc:
        return False, "", str(exc)
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _run_inline_tests(
    code: str, tests: list[str], timeout: int, sandbox: bool
) -> tuple[bool, str, str]:
    """Append assert lines to the generated code and execute the combined script."""
    test_block = "\n".join(tests)
    combined = code + f"\n\n# ── inline tests ──\n{test_block}\n"

    if sandbox:
        bad = _check_dangerous_imports(combined)
        if bad:
            return False, "", f"[SANDBOX] Blocked dangerous import(s): {', '.join(bad)}"

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(combined)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [sys.executable, tmp_path],
            capture_output=True,
            timeout=timeout,
        )
        stdout = result.stdout.decode(errors="replace").strip()
        stderr = result.stderr.decode(errors="replace").strip()
        return result.returncode == 0, stdout, stderr
    except subprocess.TimeoutExpired:
        return False, "", f"Inline tests timed out after {timeout}s"
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _run_test_script(generated_path: str, test_script_path: str, timeout: int) -> tuple[bool, str, str]:
    """Run an external test file, injecting the generated module path as an env var."""
    import os
    env = {**os.environ, "GENERATED_MODULE": generated_path}
    try:
        result = subprocess.run(
            [sys.executable, test_script_path],
            capture_output=True,
            timeout=timeout,
            env=env,
        )
        stdout = result.stdout.decode(errors="replace").strip()
        stderr = result.stderr.decode(errors="replace").strip()
        return result.returncode == 0, stdout, stderr
    except subprocess.TimeoutExpired:
        return False, "", f"Test script timed out after {timeout}s"


# ── Iteration metadata ─────────────────────────────────────────────────────────

def save_attempt(
    output_dir: Path,
    fail_count: int,
    code: str,
    stdout: str,
    stderr: str,
    feedback: str,
    model: str,
) -> None:
    """Save all artefacts for one failed attempt into attempts/NNN/."""
    attempt_dir = output_dir / "attempts" / f"{fail_count:03d}"
    attempt_dir.mkdir(parents=True, exist_ok=True)

    (attempt_dir / "code.py").write_text(code)
    (attempt_dir / "stdout.txt").write_text(stdout)
    (attempt_dir / "stderr.txt").write_text(stderr)
    (attempt_dir / "manager_feedback.txt").write_text(feedback)
    (attempt_dir / "model.txt").write_text(model)

    # Legacy flat fail-N.py for easy browsing
    (output_dir / f"fail-{fail_count}.py").write_text(code)

    print(f"[SAVED]  attempts/{fail_count:03d}/ + fail-{fail_count}.py")


# ── Main pipeline ──────────────────────────────────────────────────────────────

def run_pipeline(args: argparse.Namespace) -> None:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    sandbox = not args.no_sandbox
    timeout = args.timeout

    print(f"\n{'═'*62}")
    print(f"  Ollama Code-Gen Pipeline  (sandbox={'ON' if sandbox else 'OFF'})")
    print(f"{'═'*62}")

    # 1. Parse task file
    print(f"[TASK]  {args.task_file}")
    task = parse_task_file(args.task_file)
    print(f"[TASK]  {task['task'][:80]}{'…' if len(task['task']) > 80 else ''}")
    if task["expected_output"]:
        print(f"[EXPECTED] {repr(task['expected_output'][:60])}")
    if task["inline_tests"]:
        print(f"[TESTS] {len(task['inline_tests'])} inline assert test(s)")
    if task["test_script"]:
        print(f"[TEST_SCRIPT] {task['test_script']}")

    # 2. Resolve coder models
    available = list_ollama_models()
    requested = args.models or DEFAULT_MODELS
    if available:
        coder_models = [m for m in requested if m in available]
        if not coder_models:
            print(f"[WARN] None of {requested} found locally (available: {available}). Using as-is.")
            coder_models = requested
    else:
        print("[WARN] Could not enumerate Ollama models; using provided names.")
        coder_models = requested

    # 3. Manager picks initial order
    print(f"\n[MANAGER] '{MANAGER_MODEL}' planning initial route…")
    next_model = manager_plan(task, coder_models)[0]

    # 4. Iterative generation loop
    iteration  = 0   # total loop counter (includes skipped empty responses)
    fail_count = 0   # files actually written
    history: list[dict] = []   # rich history passed to models and manager

    print(f"\n[PIPELINE] Max {args.max_iterations} iterations  |  Models: {coder_models}\n")

    while iteration < args.max_iterations:
        iteration += 1
        model = next_model
        print(f"[ITER {iteration:02d}]  model={model}")

        # Generate
        feedback = history[-1]["manager_feedback"] if history else ""
        code = generate_code(model, task, history, feedback)

        if not code:
            print(f"[ITER {iteration:02d}]  Empty response — skipping (iteration counter does not advance file count)")
            continue

        # Test
        success, stdout, stderr = test_script(code, task, timeout, sandbox)

        # Record in history regardless of outcome
        record = {
            "attempt": fail_count + 1,
            "model":   model,
            "code":    code,
            "stdout":  stdout,
            "stderr":  stderr,
            "manager_feedback": "",
        }

        if success:
            success_path = output_dir / "success.py"
            success_path.write_text(code)
            print(f"\n{'═'*62}")
            print(f"  ✓  SUCCESS — iteration {iteration}, model '{model}'")
            print(f"     {success_path}")
            print(f"{'═'*62}\n")
            return

        # Failure path
        fail_count += 1
        route = manager_route(task, coder_models, history + [record])
        record["manager_feedback"] = route["feedback"]
        history.append(record)

        save_attempt(output_dir, fail_count, code, stdout, stderr, route["feedback"], model)

        print(f"[ITER {iteration:02d}]  FAILED")
        print(f"  expected : {repr(task['expected_output'][:60])}")
        print(f"  got      : {repr(stdout[:60])}")
        if stderr:
            print(f"  stderr   : {stderr[:120]}")
        print(f"[MANAGER] → next: '{route['next_model']}'  reason: {route['reason'][:80]}")
        print(f"[MANAGER] feedback: {route['feedback'][:200].replace(chr(10), ' ')}")
        print()

        next_model = route["next_model"]

    print(f"\n[PIPELINE] Reached max iterations ({args.max_iterations}) — no success.")
    print(f"[PIPELINE] Artefacts in: {output_dir}/attempts/")


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Multi-model Ollama code-generation pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("task_file", help="Path to task definition file")
    parser.add_argument("--output-dir", "-o", default=DEFAULT_OUTPUT_DIR,
                        help="Output directory (default: .)")
    parser.add_argument("--max-iterations", "-n", type=int, default=DEFAULT_MAX_ITER,
                        help=f"Max attempts (default: {DEFAULT_MAX_ITER})")
    parser.add_argument("--models", "-m", nargs="+",
                        help="Coder models (overrides defaults)")
    parser.add_argument("--manager", default=MANAGER_MODEL,
                        help=f"Manager model (default: {MANAGER_MODEL})")
    parser.add_argument("--timeout", type=int, default=SCRIPT_TIMEOUT,
                        help=f"Script execution timeout in seconds (default: {SCRIPT_TIMEOUT})")
    parser.add_argument("--no-sandbox", action="store_true",
                        help="Disable dangerous-import check (use only with trusted tasks)")

    args = parser.parse_args()

    global MANAGER_MODEL
    MANAGER_MODEL = args.manager

    run_pipeline(args)


if __name__ == "__main__":
    main()